server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**
            - id: product-service-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
